server:
  port: 8085
spring:
  application:
    name: spring-boot-app
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_book_app
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


